### ISSUE TITLE
Is this repository serving any purpose?

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacypipe-dir#5]
This appears to be *data* not code. The data are old, and already archived elsewhere.

**Comment by moustakas** [comment]
Indeed, the data here are obsolete, and we've moved to a much better production model. However, are *all* these files somewhere?  If so, then I guess we could shut down or remove this repo.

**Comment by weaverba137** [comment]
I will double-check.

**Comment by weaverba137** [comment]
* All branches are stale, by years.
* On the master branch:
  * calib/se-config/ 
    - Looks like a copy of /global/project/projecdirs/cosmo/data/legacysurvey/dr4/calib/se-config/
    - 200bbc759ee appears to have happened after DR4.
  * images/ : Just contains a bunch of symlinks to directories at NERSC.  Would be useless elsewhere.
  * Top-level files
    - Yet another copy of the Tycho2 catalog.
    - Intermediate versions of the `survey-ccds-(bass|mzls).fits.gz` files.
    - Copies of the survey-bricks files.

Conclusion: nothing obviously worth saving.

**Comment by moustakas** [comment]
Excellent, thanks.  I'm OK with blowing away this repo but maybe @dstndstn should sign off, too?

**Comment by dstndstn** [comment]
Go for it!  Thank you for the careful checking.

**Comment by weaverba137** [comment]
OK, I will take care of it presently.
